{
 "title": "nae_benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Device Running Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Device CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode=~\"(system|user|nice|iowait|irq|softirq|steal)\"}[5s])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5s])) * 100)",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Device Main Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "MemAvailable" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "MemFree" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "MemTotal" }
   ]
  },
  {
   "title": "Device File System Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes)",
     "legendFormat": "FS_Available"
    },
    {
     "expr": "sum(node_filesystem_free_bytes)",
     "legendFormat": "FS_Free"
    },
    {
     "expr": "node_memory_Inactive_file_bytes",
     "legendFormat": "FS_Inactive"
    }
   ]
  },
  {
   "title": "Daemon Resident Main Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{memtype=\"resident\"}[15h]",
     "legendFormat": "{{groupname}}"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{memtype=\"resident\", groupname=~\"(hpe-tsdbd|hpe-policyd|prometheus)\"})[15h:3s]",
     "legendFormat": "NAE Total"
    }
   ]
  },
  {
   "title": "Daemon CPU (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (groupname) (rate(namedprocess_namegroup_cpu_seconds_total[5s]))[6h:2s]",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "hpe-tsdbd Memory Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"switch_prom_collector\"}[8h]",
     "legendFormat": "Total Claimed from OS"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"switch_prom_collector\"}[8h]",
     "legendFormat": "Heap Inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"switch_prom_collector\"}[8h]",
     "legendFormat": "Idle Heap"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"switch_prom_collector\"}[8h]",
     "legendFormat": "Stack Inuse"
    },
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"switch_prom_collector\"}[10s])",
     "legendFormat": "malloc/sec"
    },
    {
     "expr": "rate(go_memstats_frees_total{job=\"switch_prom_collector\"}[10s])",
     "legendFormat": "free/sec"
    }
   ]
  },
  {
   "title": "TSDBD Notification Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hpe_tsdbd_telemetry_summaries[10h]",
     "legendFormat": "{{type}} {{quantile}}th"
    }
   ]
  },
  {
   "title": "Number of gorutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"switch_prom_collector\"}[8h]",
     "legendFormat": "hpe-tsdbd"
    }
   ]
  },
  {
   "title": "Notification Ratios",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "hpe_tsdbd_telemetry_counters{type=\"processed_notifications\"} / on (instance) hpe_tsdbd_telemetry_counters{type=\"incoming_notifications\"}",
     "legendFormat": "% Processed"
    },
    {
     "expr": "hpe_tsdbd_telemetry_counters{type=\"dropped_notifications\"} / on (instance) hpe_tsdbd_telemetry_counters{type=\"incoming_notifications\"}",
     "legendFormat": "% Dropped"
    },
    {
     "expr": "hpe_tsdbd_telemetry_counters{type=\"stale_notifications\"} / on (instance) hpe_tsdbd_telemetry_counters{type=\"incoming_notifications\"}",
     "legendFormat": "% Stale"
    }
   ]
  },
  {
   "title": "TSDBD events",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hpe_tsdbd_telemetry_counters{type=~\"(processed_notifications|dropped_notifications|incoming_notifications)\"}[10s])[10h:3s]",
     "legendFormat": "{{type}}/sec"
    }
   ]
  },
  {
   "title": "TSDBD Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hpe_tsdbd_telemetry_counters[10h]",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "TSDBD Database Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(benchmark_tsdbd_database_requests[10s])",
     "legendFormat": "{{operation}}-{{table}}/sec"
    }
   ]
  },
  {
   "title": "TSDBD Database Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "benchmark_tsdbd_database_requests",
     "legendFormat": "{{operation}}-{{table}}"
    }
   ]
  },
  {
   "title": "TSDBD Alert Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hpe_tsdbd_telemetry_counters{type=\"prometheus_condition_alerts\"}[10s])",
     "legendFormat": "Condition Alerts/sec"
    },
    {
     "expr": "rate(hpe_tsdbd_telemetry_counters{type=\"condition_events\"}[10s])",
     "legendFormat": "Condition Events/sec"
    }
   ]
  },
  {
   "title": "Total Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_write_bytes_total",
     "legendFormat": "{{groupname}} write"
    },
    {
     "expr": "namedprocess_namegroup_read_bytes_total",
     "legendFormat": "{{groupname}} read"
    }
   ]
  },
  {
   "title": "Open File Descriptors (FDs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Daemon Num Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_threads",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "daemon Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Daemon page faults",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_thread_minor_page_faults_total + namedprocess_namegroup_thread_major_page_faults_total",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Daemon Context Switching/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_context_switches_total[5s])",
     "legendFormat": "{{groupname}}-{{ctxswitchtype}}"
    }
   ]
  },
  {
   "title": "Metric Collector CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5s])*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Metric Collector Main Memory Footprint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}} Resident" },
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} Go Alloc" },
    { "expr": "go_memstats_gc_sys_bytes", "legendFormat": "{{job}} Go GC" }
   ]
  },
  {
   "title": "Device Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "Allocated FDs" },
    {
     "expr": "sum(node_filesystem_files_free)",
     "legendFormat": "Free Files"
    },
    { "expr": "sum(node_filesystem_files)", "legendFormat": "No. Files" }
   ]
  },
  {
   "title": "Device Disk Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes)",
     "legendFormat": "Disk Capacity"
    }
   ]
  }
 ]
}